### ISSUE TITLE
Template: use key property containing slash, quote, or point.

### ISSUE THREAD

**Issue by julientard** [argoproj-labs/argocd-notifications#108]
Hello, 

In a template, i'm trying to use a property containing dash or point characters without sucess. I tried with quote, double quotes, and brackets. 
For example : {{.app.metadata.annotations.app-revision}} or {{.app.metadata.annotations.mywebsite.com/apprevision}}

Am i missing something ? Or is it just not possible for now ?

**Comment by ryota-sakamoto** [comment]
Hi @julientard 

You can use follows template.
`{{index . "app" "metadata" "annotations" "app-revision"}}`

https://golang.org/pkg/text/template/#hdr-Functions
