### ISSUE TITLE
I have a question about setting up slack in argocd-notifications-secret's notifiers.yaml.

### ISSUE THREAD

**Issue by BangShinChul** [argoproj-labs/argocd-notifications#11]
Hello! 😃 

I am very interested in your work.
I've been waiting for the notification feature on the Argo CD.
Thank you for your works!

Back to the point, so I tried to test your project right away.
Back to the point
So I tried to test your project right away.

But setting up Slack is too difficult.
I'm wonder that what tokens does <my-token> mean in the https://argoproj-labs.github.io/argocd-notifications/ documentation?
How can I find this token?

Please Let me know.
Thank you.

**Comment by muenchdo** [comment]
First you need to create a new App in your Slack workspace: https://api.slack.com/apps?new_app=1

Then, in _OAuth & Permissions_, add a new OAuth scope `chat:write:bot`. Scroll up and click _Install App to Workspace_ and complete the setup. Afterwards you will see the OAuth Access Token which you can use for Argo CD notifications.

I hope that helps 🙂

**Comment by BangShinChul** [comment]
@muenchdo 
Wow! Thank you for your reply!
Your answer was very helpful 😄

**Comment by BangShinChul** [comment]
@muenchdo 

Can I ask additional questions?

As you answered, I created a Slack App and received an OAuth token for `chat:write:bot` And I set a argocd-notifications-secret with this token.
But the message doesn't come to my slack channel.. 😢 

Here's what I worked on:

Copied the contents of `https://raw.githubusercontent.com/argoproj-labs/argocd-notifications/stable/manifests/install.yaml` in my local.

And I edited as below :

```
...
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  config.yaml: |
    triggers:
      name: on-sync-succeeded
        condition: on-sync-succeeded
        template: app-sync-succeeded
        enabled: true
    templates:
      name: app-sync-status
        title: Application {{.app.metadata.name}} sync status is {{.app.status.sync.status}}
        body: |
          Application {{.app.metadata.name}} sync is {{.app.status.sync.status}}.
          Application details: {{.context.argocdUrl}} / applications / {{. App.metadata.name}}
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  notifiers.yaml: |
    slack:
      token: <My slack apps OAuth access token>
type: Opaque
...

```

Then I proceeded to apply with the following command : 
`kubectl apply -n argocd -f install.yaml`

And I changed the contents of Application distributed through Argo CD with the following command : 

my app name: test-app
my slack channel name: product-argo-cd

`kubectl patch app test-app -n argocd -p '{"metadata": {"annotations": {"recipients.argocd-notifications.argoproj.io": "slack: product-argo-cd"}}}'- type merge`

I just worked like this.
Have you missed anything?

**Comment by muenchdo** [comment]
There shouldn't be a space in your annotation, it should be `slack:product-argo-cd`. You also might need to add the Slack App to your `product-argo-cd` channel.

(I can also really recommend joining the [Argo community Slack](https://argoproj.github.io/community/join-slack))

**Comment by BangShinChul** [comment]
@muenchdo 

As you answered, I removed the whitespace and tried again, but still no message.. 😞 
As you've recommended, I'll ask you to join the Argo community Slack channel.
Thank you for your help! 👍

**Comment by alexmt** [comment]
Hello @BangShinChul ,

Thank you for trying argocd-notification! Answered the question in slack channel: https://argoproj.slack.com/archives/CSPC6G5JQ/p1579290125002700

**Comment by alexmt** [comment]
Created ticket to document slack app creation :) https://github.com/argoproj-labs/argocd-notifications/issues/12

**Comment by uttamanand-whs** [comment]
how to get it worked with existing channel on slack ? I am setting the token for the existing slack channel.
