### ISSUE TITLE
Notification on Teams

### ISSUE THREAD

**Issue by gevraud** [argoproj-labs/argocd-notifications#111]
Hello,

I was wondering if it's possible to send notifications to Microsoft Teams ?

Regards

**Comment by pasha-codefresh** [comment]
Hey, @alexmt we are taking it

**Comment by alexmt** [comment]
thank you!

**Comment by shepely** [comment]
Hey @gevraud ,
I managed to send notifications to MS Teams using webhook support. I'll share below some details with an example, maybe someone will find it handy.
I'm using Helm Chart version `1.0.12` with `v1.0.1` release.
In `values.yaml`:

```
notifiers:
# For more information: https://argocd-notifications.readthedocs.io/en/stable/services/overview/
  service.webhook.msteams: |
    url: $msteams-kubernetes
...
subscriptions:
  # For more information: https://argocd-notifications.readthedocs.io/en/stable/subscriptions/
  - recipients:
    - msteams
    triggers: 
    - on-sync-succeeded
...
templates:
  # For more information: https://argocd-notifications.readthedocs.io/en/stable/templates/
  template.app-sync-succeeded: |
    webhook:
      msteams:
        method: POST 
        body: |     
          {
            "@type": "MessageCard",
            "@context": "http://schema.org/extensions",
            "themeColor": "0076D7",
            "summary": "{{.app.spec.destination.namespace}}/{{.app.metadata.name}} sync status is {{.app.status.sync.status}}",
            "sections": [
              {
                "activityTitle": "{{.app.spec.destination.namespace}}/{{.app.metadata.name}} sync status is {{.app.status.sync.status}}",
                "facts": [
                  {
                    "name": "Repository",
                    "value": "{{.app.spec.source.repoURL}}"
                  },
                  {
                    "name": "Synced at",
                    "value": "{{.app.status.operationState.finishedAt}}"
                  },
                  {
                    "name": "Sync status",
                    "value": "{{.app.status.sync.status}}"
                  }
                ],
                "markdown": true
              }
            ],
            "potentialAction": [
              {
                "@type": "OpenUri",
                "name": "Details",
                "targets": [
                  {
                    "os": "default",
                    "uri": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
                  }
                ]
              }
            ]
          } 
...
```

And in `secrets.yaml`:
```
secret:
    items:
        msteams-kubernetes: <encrypted-webhook-url>
...
```

As a result I got a notification:
![image](https://user-images.githubusercontent.com/9297775/107013228-60b48580-679a-11eb-97b0-0272ca8e66a4.png)

Some MS docs on creating message cards: https://docs.microsoft.com/en-us/outlook/actionable-messages/send-via-connectors.

@pasha-codefresh I'd love to see built-in templates for MS Teams messages 🙏 Let me know, if I can be any help there.

**Comment by alexmt** [comment]
Implemented by https://github.com/argoproj-labs/argocd-notifications/pull/181

**Comment by dandeshsanshi** [comment]
Team,
I am getting this error, can anyone help 
time="2021-06-30T15:14:22Z" level=info msg="Trigger on-sync-succeeded result: [{[0].zxM90Et6k4Elb1-fHdjtDJq0xR0  [app-sync-succeeded] true}]" app=argocd/dev-app-eks-cluster-2-tableau-reporting
time="2021-06-30T15:14:22Z" level=info msg="Sending notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' to '{teams channelName}'" app=argocd/dev-app-eks-cluster-2-tableau-reporting
time="2021-06-30T15:14:22Z" level=error msg="Failed to notify recipient {teams channelName} defined in app argocd/dev-app-eks-cluster-2-tableau-reporting: notification service 'teams' is not supported" app=argocd/dev-app-eks-cluster-2-tableau-reporting
time="2021-06-30T15:14:22Z" level=info msg="Processing completed" app=argocd/dev-app-eks-cluster-2-tableau-reporting
time="2021-06-30T15:14:22Z" level=info msg="Start processing" app=argocd/dev-app-eks-cluster-2-financial-reporting
time="2021-06-30T15:14:22Z" level=info msg="Trigger on-sync-succeeded result: [{[0].zxM90Et6k4Elb1-fHdjtDJq0xR0  [app-sync-succeeded] true}]" app=argocd/dev-app-eks-cluster-2-financial-reporting
time="2021-06-30T15:14:22Z" level=info msg="Sending notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' to '{teams channelName}'" app=argocd/dev-app-eks-cluster-2-financial-reporting
time="2021-06-30T15:14:22Z" level=error msg="Failed to notify recipient {teams channelName} defined in app argocd/dev-app-eks-cluster-2-financial-reporting: notification service 'teams' is not supported" app=argocd/dev-app-eks-cluster-2-financial-reporting

**Comment by dandeshsanshi** [comment]
I configured Argocd-Notifications with Teams channel with latest versions of Argocd-Notifications 
but I got the above error.

**Comment by sidiney-crescencio** [comment]
> I configured Argocd-Notifications with Teams channel with latest versions of Argocd-Notifications
> but I got the above error.

I was also getting the same error, which version of argocd-notifications are you using? Likely 1.0.2, as it was my case 

You need to upgrade to 1.1.1 

https://github.com/argoproj-labs/argocd-notifications/releases/tag/v1.1.1
