### ISSUE TITLE
User "system:serviceaccount:argocd:argocd-notifications-bot" cannot list resource "secrets" in API group "" in the namespace "argocd"

### ISSUE THREAD

**Issue by xakraz** [argoproj-labs/argocd-notifications#112]
Hi there, 

I have just deployed `argocd-notifications-bot` following the [doc](https://argoproj-labs.github.io/argocd-notifications/recipients/bot/) by doing:

```
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj-labs/argocd-notifications/v0.6.1/manifests/install-bot.yaml
```

And I have got this error.

```
E0728 15:37:24.517042       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191114101535-6c5935290e33/tools/cache/reflector.go:96: Failed to list *v1.Secret: secrets "argocd-notifications-secret" is forbidden: User "system:serviceaccount:argocd:argocd-notifications-bot" cannot list resource "secrets" in API group "" in the namespace "argocd"
```

I have checked on the latest version `v0.7.0` and `stable` but it does not seem to be "fixed".

As a workaround, I have updated the role `argocd-notifications-bot` with

```
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - watch
```

like the role `argocd-notifications-controller` 's one.

**Comment by miltonstrat** [comment]
I just faced the same issue and your workaround worked here at least for the error message until now..

**Comment by alexmt** [comment]
Fixed
