### ISSUE TITLE
Unable to call the function to get Commit Metadata

### ISSUE THREAD

**Issue by raogayathri** [argoproj-labs/argocd-notifications#113]
Making a function call "{{(call .repo.GetCommitMetadata .app.status.sync.revision).Author}}" to get the author information, gives the error
<call .repo.GetCommitMetadata .app.status.sync.revision>: error calling call: call of nil". I am using 1.5.1 version of ArgoCD. Did anyone else face this error? How can we fix this?

**Comment by alexmt** [comment]
Hello @raogayathri ,

Most likely the application does not have `.app.status.sync` field. So template fails when trying to access `revision` field of nil. I suggest adding nil check into trigger condition. E.g.

```
app.status != nil
```

**Comment by shashanklmurthy** [comment]
> Hello @raogayathri ,
> 
> Most likely the application does not have `.app.status.sync` field. So template fails when trying to access `revision` field of nil. I suggest adding nil check into trigger condition. E.g.
> 
> ```
> app.status != nil
> ```

Here's the error I'm getting @alexmt 


```
<call .repo.GetCommitMetadata .app.status.sync.revision>: error calling call: call of nil
```

This seems to suggest that `.repo.GetCommitMetadata` is nil rather than `.app.status`. I double checked my `Application` manifest and the status and underlying sync fields are populated with the right revision

**Comment by isena** [comment]
Most likely argocd-notifications version is not >= 0.7.0

**Comment by alexmt** [comment]
Thank you for sharing the solution @isena !
