### ISSUE TITLE
ArgoCD Notifications for OutOfSync status

### ISSUE THREAD

**Issue by raogayathri** [argoproj-labs/argocd-notifications#118]
I have a requirement to send notification every time status is changed to OutOfSync from OutOfSync but for different revision. This does not seem to be working right now. Notification is being sent only when status changed from some other status to outofsync but not when outofsync state remains but for different revision.  Please let me know if there is any way to add a condition to check for revision change as well along with app.status.sync.status == 'OutOfSync' condition.

**Comment by alexmt** [comment]
Hello @raogayathri ,

This behavior is not supported right now. Changes proposed in https://github.com/argoproj-labs/argocd-notifications/issues/60#issuecomment-599811649 should enable it.

**Comment by alexmt** [comment]
Implemented
