### ISSUE TITLE
Proposal: Enables to output log in JSON

### ISSUE THREAD

**Issue by shokada** [argoproj-labs/argocd-notifications#123]
# Summary
I want to be able to format the log output as json.

# Motivation
I want to have a structured log output so that i extract metrics from the log using something like `mtail`.

# Proposal
Implement the same way as `argocd-application-controller`
https://github.com/argoproj/argo-cd/blob/v1.7.7/cmd/argocd-application-controller/main.go#L122
https://github.com/argoproj/argo-cd/blob/v1.7.7/cmd/argocd-application-controller/main.go#L64

**Comment by alexmt** [comment]
Agree with the proposal. Thank you for pointing to existing implementation @shokada

**Comment by shokada** [comment]
@alexmt Thank you for agreeing to this proposal. I will submit the PR for this.
