### ISSUE TITLE
static configmap and secret binding

### ISSUE THREAD

**Issue by mnacharov** [argoproj-labs/argocd-notifications#136]
Hi folks!

I just checked out this utility. Looks great - flexible and easy to use.

But one thing stops me from using in production:  looks like there is no way to bind secret and configmap to deployment, and disable secret and configmap access from the Role spec. 

Is it possible to change ?

**Comment by alexmt** [comment]
hello @mnacharov ,

Just want to confirm I understand it the right way. You want to restrict controller permission to only one secret and config map, right?

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj-labs/argocd-notifications/pull/199

**Comment by mnacharov** [comment]
Great! Thank you!
