### ISSUE TITLE
Change ArgoCD URL

### ISSUE THREAD

**Issue by hazarguney** [argoproj-labs/argocd-notifications#139]
Hello everyone!

In every notification, address is used as `https://localhost:4000`, how can we change this?

**Comment by alschade** [comment]
In your `config.yaml` block, you can set `context.argocdUrl` to the url of your specific deployment to override the default value.

**Comment by Mr-istov** [comment]
Hello, like @alschade mentioned you can specify that in the `config.yaml`, you can see an example and a similar question asked here: https://github.com/argoproj-labs/argocd-notifications/issues/67

**Comment by hazarguney** [comment]
Thank you.

**Comment by atbee** [comment]
You need to add the custom `config.yaml` data in `argocd-notifications-cm` ConfigMap.
```diff
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
+  config.yaml: |
+    context:
+      argocdUrl: <YOUR_ARGOCD_URLargocd>
  ...
```
