### ISSUE TITLE
feat: Triggers on argo-rollout statuses

### ISSUE THREAD

**Issue by alschade** [argoproj-labs/argocd-notifications#140]
As part of our GitOps strategy, our pipelines build application artifacts and configurations which are then rolled out in ArgoCD, using argo-rollouts. While the sync status provides some useful feedback on the status of the deployment, we really want to let users know if their rollouts were successful, since that is the goal of the argo deployment in our setup.

Maybe it's already possible, but I don't know where in the context objects this information would be stored.

**Comment by alexmt** [comment]
This is no possible yet but we are planning to support it. Argo CD notifications was [redesigned](https://docs.google.com/document/d/1nw0i7EAehNnjEkbpx-I3BVjfZvRgetUFUZby4iMUSWU/edit#heading=h.efmu907hcczu) to accommodate Rollouts use cases. The next step is to move https://github.com/argoproj-labs/argocd-notifications/tree/master/pkg into separate repo that will be consumed by Argo Rollouts.

**Comment by ryota-sakamoto** [comment]
this feature is developing on https://github.com/argoproj/argo-rollouts/issues/369
