### ISSUE TITLE
Allow multi recipients of webhook notifications by app-level annotations

### ISSUE THREAD

**Issue by jacobsin** [argoproj-labs/argocd-notifications#141]
https://github.com/argoproj-labs/argocd-notifications/blob/4c55a549111a96ba6fc46bd7d4552b671a43e915/pkg/api.go#L52

At the moment the webhook service body gotemplate can only source **single** recipient via app.metadata.annotations, would be ideal if **multiple** recipients can be provided similarly to slack service

Looks like it can be simply achieved by adding `dest.Recipient` to `in`, similar to `dest.Service`

**Comment by jacobsin** [comment]
Looks like this will also help in the case when subscription are declared at AppProject level

**Comment by alexmt** [comment]
Hello @jacobsin ,

Great suggestion! I agree, there might be cases when the recipient can be used e.g. as part of a URL path. I like your suggestion to provide the recipient as one more "system" variable. Thank you!
