### ISSUE TITLE
Trying to retrieve helm values files parameters in templates

### ISSUE THREAD

**Issue by paydaycay** [argoproj-labs/argocd-notifications#150]
Hi,

First, thanks for this project ! It's awesome. :)

Is there a way to get helm values files parameters in templates ? 

As argocd show all parameters in AppDetails/Parameters, I thought it could be possible but I can't find a way to make it work in argocd-notifications.

If not, would it be hard to implement ?

**Comment by alexmt** [comment]
Hello @paydaycay .

Yes, this is possible. The application details might be exposed via `repo.GetAppDetails` function, similarly to [repo.GetCommitMetadata](https://argocd-notifications.readthedocs.io/en/stable/triggers_and_templates/functions/#repo) function. Behind the scene, Argo CD notifications call Argo CD repo server API:

https://github.com/argoproj-labs/argocd-notifications/blob/dc9984c81b1b63758ccf6061856c8a4e6c8a49aa/expr/repo/repo.go#L29

**Comment by paydaycay** [comment]
Thanks for your answer @alexmt :) I'll try to see what I can do to contrib on this then. But I never developed in Go so I don't know if I will be able to implement this. ^^

**Comment by paydaycay** [comment]
Hi @alexmt, I'm currently trying to implement this feature.
I'm facing issues due to my unknowledge of go I guess.
To call `svc.repoServerClient.GetAppDetails` in my method in service.go file, I need to create an instance of `RepoServerAppDetailsQuery`.
To create it, I need : 

- `Repo string` : already done in GetCommitMetada so it was easy
- `Repos []*v1alpha1.Repository`: this field is the list Helm Repos so I retrieved it from argcdDB (`argocdDB.ListHelmRepositories(ctx)`)
- `Source *v1alpha1.ApplicationSource` : It seems to be in the app field (in repo.go) but I don't know how to retrieve it from the `app *unstructured.Unstructured`
- `KustomizeOptions *v1alpha1.KustomizeOptions` : It seems to be findable in [Server](https://github.com/argoproj/argo-cd/blob/94eba091ba1df482263ca4186724e6d17e59de99/server/application/application.go#L251) but I don't know how to get it from service.go or repo.go

I hope you will be able to help me because I'm stuck :(

**Comment by alexmt** [comment]
Hello @paydaycay , 

Thank you for working on this feature! You might use `scheme.Scheme.Convert` from k8s client:

```golang

import (
	"k8s.io/client-go/kubernetes/scheme"
	"github.com/argoproj/argo-cd/pkg/apis/application/v1alpha1"
)

func init() {
	_ = v1alpha1.SchemeBuilder.AddToScheme(scheme.Scheme)
}

func getApplicationSource(obj *unstructured.Unstructured) (*v1alpha1. ApplicationSource, error) {
	application := &v1alpha1.Application{}
	err := scheme.Scheme.Convert(obj, application, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to convert %T to %T: %v", obj, application, err)
	}

	return &application.Spec.Source, nil
}
```

another option is to marshal unstructured to json and unmarshal back to `v1alpha1.Application`:

```golang
func getApplicationSource(obj *unstructured.Unstructured) (*v1alpha1. ApplicationSource, error) {
	data, err := json.Marshal(obj)
	if err != nil {
		return nill, err
	}
	application := &v1alpha1.Application{}
	err = json.Unmarshal(data, application)
	if err != nil {
		return nill, err
	}
	return &application.Spec.Source, nil
}
```

**Comment by paydaycay** [comment]
Thanks @alexmt !
Is there a better practice between both ?
And any idea how I can retrieve KustomizeOptions ? 
Thanks for all !

**Comment by alexmt** [comment]
Oh, right. KustomizeOptions are available in settings manager:

```golang
func getKustomizeOptions(source * ApplicationSource) (*v1alpha1. KustomizeOptions, error) {
	kustomizeSettings, err := settingsMgr.GetKustomizeSettings()
	if err != nil {
		return nil, err
	}
	return kustomizeSettings.GetOptions(source)
}
```

> Is there a better practice between both ?

The `scheme.Scheme.Convert` should have better performance, I would try it first.
