### ISSUE TITLE
GetAppDetails Helm example using html/template in documentation

### ISSUE THREAD

**Issue by Zava2012** [argoproj-labs/argocd-notifications#175]
Hello!
First of all, I want to thank you for all your products!
And I want to ask you about `repo.GetAppDetails() AppDetail` functionality.
I tried to output app deploy type using `{{(call .repo.GetAppDetails).Type}}` but without any success: `error calling call: call of nil`.
My goal is to get few Helm values and send them to Slack.

It will be great if documentation have an example how to use it with html/template :)

Thanks!

**Comment by alexmt** [comment]
Hello @Zava2012 , `repo.GetAppDetails` is not released yet. It will be available in v1.1 .

**Comment by Zava2012** [comment]
Hello @alexmt !
Thank you for your answer!
Then I'll be waiting for this functionality. Thank you!)
You can close this issue.

**Comment by musabmasood** [comment]
> Hello @Zava2012 , `repo.GetAppDetails` is not released yet. It will be available in v1.1 .
 
Is this released yet? Getting `<call .repo.GetAppDetails>: error calling call: runtime error: invalid memory address or nil pointer dereference` and I'm on the latest release atm v1.1.1

**Comment by musabmasood** [comment]
@alexmt getting a `nil pointer` error on this `v1.1.1`

**Comment by ryota-sakamoto** [comment]
Hi @mayzhang2000 
I'll check it, so would you open a new issue, please?
I think it is a bug.

**Comment by alexmt** [comment]
It is a bug indeed. Fixed by https://github.com/argoproj-labs/argocd-notifications/pull/267
