### ISSUE TITLE
Multi-line commit message (GetCommitMetadata.Message)

### ISSUE THREAD

**Issue by guyelia** [argoproj-labs/argocd-notifications#182]
Hey, 
I'm using the `repo.GetCommitMetadata.Message` function in a slack messages.
My commits are multi-lines, but I didn't get them, only the first line.
function usage in the template:
```
{
 "title": "Commit",
 "value": "{{(call .repo.GetCommitMetadata .app.status.sync.revision).Message}}",
 "short": true
}
```
the original commit message:
```
Set SERVICE to version v1.1.1 on environment

username

line3
```
slack integration output:
```
Commit:
Set SERVICE to version v1.1.1 on environment
```

Is it possible to display all the lines?

Thanks!

**Comment by ryota-sakamoto** [comment]
Hi @guyelia 

I checked it.
It is specification of argo-cd, so you can not use multiline message.
https://github.com/argoproj/argo-cd/blob/v1.8.0/reposerver/repository/repository.go#L1236-L1237

**Comment by alexmt** [comment]
It was changed in 1.9 Argo CD version (not released yet). After Argo CD v1.9 release commit message won't be truncated

**Comment by alexmt** [comment]
Closing the issue
