### ISSUE TITLE
Slack messages format from phone devices

### ISSUE THREAD

**Issue by Zava2012** [argoproj-labs/argocd-notifications#185]
Hello!
I noticed an interesting thing that when I watch on the messages from Slack Desktop they looks like this:
**Commit:** `asdfghjklqwertyui345yhjd`

But when I watching on the messages from Slack mobile application they looks like this (without formatting):
```
*Commit:* `asdfghjklqwertyui345yhjd`
```

**Comment by ryota-sakamoto** [comment]
Hi @Zava2012 
It is Slack mobile app problem because argocd-notifications just send json request.
