### ISSUE TITLE
Catalog install.yaml not updated for latest release

### ISSUE THREAD

**Issue by aywrite** [argoproj-labs/argocd-notifications#186]
I noticed that #156/#157 was included in release 1.0.2 but the fix wasn't propagated to the [install.yaml](https://github.com/argoproj-labs/argocd-notifications/blob/v1.0.2/catalog/install.yaml). Not sure if this is meant to be part of the CI process or just manually kept in sync with files in the catalog folder?

If it is manually kept in sync I'm happy to do a PR to fix this but wasn't sure of the normal release workflow.

**Comment by alexmt** [comment]
Hello @aywrite ! thank you for catching it!

The `make generate` is supposed to refresh all generated files. Looks like we forgot to do it. We should run `make generate` as part of CI and check that no files changed. If you have time to do it then PR would be very welcome!

**Comment by ryota-sakamoto** [comment]
fixed by #214
