### ISSUE TITLE
Missing metric: argocd_notifications_trigger_eval_total

### ISSUE THREAD

**Issue by EdYa** [argoproj-labs/argocd-notifications#195]
Hello, 

I'm using argocd-notifications 1.0.2. The monitoring metric "argocd_notifications_trigger_eval_total" is not available on the metrics endpoint.

**Comment by ryota-sakamoto** [comment]
Hi @alexmt 
Do you know the reason of deleting this metrics?
https://github.com/argoproj-labs/argocd-notifications/commit/528d3a1a6f01be0d639a80119f462cc76825e971#diff-3c5bb5f48211873c58fcba055dcae2ac7b1958969219e06e1508d76d485dace7L189

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj-labs/argocd-notifications/pull/213
