### ISSUE TITLE
Slack with incoming webhook

### ISSUE THREAD

**Issue by eddycharly** [argoproj-labs/argocd-notifications#198]
Sorry if it's a dumb question.

I'm trying to send a slack notification using a slack app incoming webhook but i'm not sure if i'm supposed to use a slack or webhook notification service (from the `argocd-notifications` point of view).

Can someone help clarify the correct notification service ?

**Comment by ryota-sakamoto** [comment]
Hi @eddycharly 

If you want to use incoming webhook, you use webhook.
On the other hand, you can use slack api with token, you can use follows.
https://argocd-notifications.readthedocs.io/en/stable/services/slack/

Do you have an answer?

**Comment by eddycharly** [comment]
Closing, thanks @ryota-sakamoto !
