### ISSUE TITLE
proposal: support private channel for telegram

### ISSUE THREAD

**Issue by ryota-sakamoto** [argoproj-labs/argocd-notifications#206]
related in #196 

Currently, telegram notification service is able to only send to public channel.
Because receipt should start with @.
https://github.com/argoproj-labs/argocd-notifications/blob/4dd6b0dcd1b5b080e12a8d989f47bde5002f007e/pkg/services/telegram.go#L22

but telegram has two types, public channel and private channel.
public channel starts with `@`.
private channel starts with `-100`.

**Comment by rogeriorocha** [comment]
i upgraded image to argoprojlabs/argocd-notifications:v1.1.0 and works fine...
