### ISSUE TITLE
Watching applications in all namespaces

### ISSUE THREAD

**Issue by eddycharly** [argoproj-labs/argocd-notifications#218]
Is this possible to control the namespaces watched by argocd-notifications ?

From what i observe, if it is not deployed in the same namespace as argocd itself (and probably in the namespace where applications are located) nothing happens.

**Comment by ryota-sakamoto** [comment]
@eddycharly 
It means that you want to deploy another namespace of application resource except argocd namespace ,  right?

**Comment by eddycharly** [comment]
Basically yes, I thought about putting applications in the namespace the applications belong to. 
Not sure if it’s supported by Argocd itself though. 

at least, when I deployed argocd-notifications in a different namespace as argocd, the notifications didn’t trigger (argocd-notifications didn’t see the applications I believe).

**Comment by sergeyshevch** [comment]
@eddycharly As i see in code, you can specify `--namespace` argument in controller deployment
https://github.com/argoproj-labs/argocd-notifications/blob/master/cmd/controller.go#L115
Have you tried it?

**Comment by eddycharly** [comment]
Thanks @sergeyshevch !
I'm going to close this issue as it seems that it's not in line with the way argo works. I feel like it doesn't make sense to have applications spread across multiple namespaces.
