### ISSUE TITLE
Support for Rocket.Chat

### ISSUE THREAD

**Issue by tobru** [argoproj-labs/argocd-notifications#233]
It would be great to see notifications to [Rocket.Chat](https://github.com/RocketChat/Rocket.Chat) directly integrated into Argo CD Notifications.

**Comment by sergeyshevch** [comment]
Hi! We are interested in this feature. May be i will try to implement it in some days

**Comment by sergeyshevch** [comment]
@alexec Can you look on my PR? After it will be merged i can add support to argocd-notifications package

**Comment by ryota-sakamoto** [comment]
Hi @sergeyshevch 
I added comment on https://github.com/argoproj/notifications-engine/pull/1

**Comment by alexmt** [comment]
Moving to https://github.com/argoproj/notifications-engine/issues/21
