### ISSUE TITLE
Support for Atlassian's Jira

### ISSUE THREAD

**Issue by AlexDHoffer** [argoproj-labs/argocd-notifications#240]
Some existing CD systems e.g. Jenkins can post build results to Jira issues as well as natively link commits in the build to those issues. See here for details: https://plugins.jenkins.io/jira/

This is a slick feature for a CD system and since Atlassian's Jira is in such widespread usage these days it would be cool to have something similar, where ArgoCD can key off a Jira issue tag in a commit message and post when a successful sync of that tag occurred back to the issue itself in Jira.

**Comment by alexmt** [comment]
Moving to https://github.com/argoproj/notifications-engine/issues/24
