### ISSUE TITLE
Template Catalog -  .app.spec.source.repoURL | call .repo.RepoURLToHTTPS broken

### ISSUE THREAD

**Issue by schoki040** [argoproj-labs/argocd-notifications#251]
Dear Team,

using `{{.app.spec.source.repoURL | call .repo.RepoURLToHTTPS}}` in teams part of 1.1.0 template catalog leads to errors.
(also tried app-sync-succeeded)

From cli:
```shell
kubectl -n argocd  exec -it argocd-notifications-controller-xxx -- /app/argocd-notifications template notify app-deployed xxx

failed to notify 'console:stdout': template: app-deployed:14:40: executing "app-deployed" at <call .repo.RepoURLToHTTPS>: error calling call: call of nil
```

After removing  `| call .repo.RepoURLToHTTPS`:
```shell
email:
  subject: New version of an application dd001 is up and running.
message: |2
   Application dd001 is now running new version of deployments manifests.
slack:
  attachments: xxx
teams:
  facts: "[{\n  \"name\": \"Sync Status\",\n  \"value\": \"Synced\"\n},\n{\n  \"name\": \"Repository\",\n  \"value\": \"https://xxx/xx.git\"\n},\n{\n  \"name\": \"Revision\",\n  \"value\": \"d19ed47f517720f25b7080ca31b0ecc5244b0205\"\n}\n\n  ,\n  \n  {\n    \"name\": \"OrphanedResourceWarning\",\n    \"value\": \"Application has 1 orphaned resources\",\n  }\n\n]\n"
  potentialAction: |-
    [{
      "@type":"OpenUri",
      "name":"Operation Application",
      "targets":[{
        "os":"default",
        "uri":"https://localhost:4000/applications/dd001"
      }]
    },
    {
      "@type":"OpenUri",
      "name":"Open Repository",
      "targets":[{
        "os":"default",
        "uri":"https://xxx/xxx.git"
      }]
    }]
  title: New version of an application dd001 is up and running.
```

**Comment by ryota-sakamoto** [comment]
Hi @schoki040 
I would like to just confirm this problem.
You have receive this error from cli only not real notification, right?
I guess this is bug of cli.

**Comment by schoki040** [comment]
Hi, correct. 

Your app-sync-template 1.1.0 is also not working for a real teams connection, but it seems above error is not the reason.
If I know more Ill open another issue.

**Comment by schoki040** [comment]
When is use it on real teams it creates the following link: https://xx.xx.int/xx/xx/xx_xx.git
Guess thats expected? I'm using HTTPS repos only, so I'm not sure it's even doing anything.

**Comment by ryota-sakamoto** [comment]
@schoki040 
This function behavior is as follows.
https://argocd-notifications.readthedocs.io/en/stable/templates/#repo
https://github.com/argoproj-labs/argocd-notifications/blob/31b8779e5fe0df245842fa531b9564facd1d3b72/expr/repo/repo_test.go#L15-L23

**Comment by schoki040** [comment]
Sorry, I can't test against usage. Maybe s.o. else can?
I looks fine, but we neither allow SSH nor http in our Git.

**Comment by ryota-sakamoto** [comment]
@schoki040 
There is no problem.
I can reproduce this issue, so I'll fix it.
