### ISSUE TITLE
Lack of detail in GitHub integration doc?

### ISSUE THREAD

**Issue by AlexDHoffer** [argoproj-labs/argocd-notifications#253]
What is the empty string here supposed to denote:

````
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.<trigger-name>.github: ""
````

I seem to be unable to set up the GitHub notification because the empty string here doesn't work and neither does setting it to my appID or installationID.

The controller reports: 

``Failed to notify recipient {github [appID|installationID]} defined in app argocd/... config is empty" ``

**Comment by ryota-sakamoto** [comment]
Hi @AlexDHoffer 
You need to configure the templates to send the GitHub notification.
https://argocd-notifications.readthedocs.io/en/stable/services/github/#templates
