### ISSUE TITLE
Annotation greater than 63 characters

### ISSUE THREAD

**Issue by jef** [argoproj-labs/argocd-notifications#255]
### Problem

I've created a webhook that seems to surpassed the 63 char limit on annotations.

How do I go about referencing my template without breaking Kubernetes?

I find it interesting as even `notifications.argoproj.io/subscribe.on-sync-status-unknown.mattermost` would break this.

Is there a different way to specify this in the `Application` CRD?

**Comment by ryota-sakamoto** [comment]
@jef 
I guess you can use `notifications.argoproj.io/subscribe.mattermost` annotation that is using defaultTrigger pattern https://argocd-notifications.readthedocs.io/en/stable/triggers/#default-triggers .

**Comment by jef** [comment]
That'll work for now! Do you think there is an alternative way to describe webhook names outside of the annotation? Or is that design intended?

**Comment by ryota-sakamoto** [comment]
@jef 
You can use default-subscriptions pattern instead of using annotation.
https://argocd-notifications.readthedocs.io/en/stable/subscriptions/#default-subscriptions

If I mistake to understand you said, please tell me more detail.

**Comment by jef** [comment]
Yes, this could also work for situations -- thanks for the links!

Sorry, let me try and be more clear.

Let's say we set default triggers and default subscriptions, and now we need to create some special webhooks that won't use any of the default triggers and we don't want it in the default subscriptions, because it's _special_.

So in this case, `notifications.argoproj.io/subscribe.on-sync-succeeded.my-longer-webhook` would not work because it goes past 63 characters. And `notifications.argoproj.io/subscribe.on-sync-succeeded.my-longer` name won't help us either because it's no longer descriptive.

Do you think there is a solution that we can use (without default triggers/subscriptions)?

If not, I thought maybe refactoring Argo CD Notifications to take the webhook name via the value of the annotation:

```
# < 63 char annotation key
# < 256 char annotation value
notifications.argoproj.io/subscribe.on-sync-succeeded: "my-really-long-webhook-name"
```

**Comment by jef** [comment]
Seems that @ryota-sakamoto is on vacation. @alexmt, did you know of any work around to this?

**Comment by ryota-sakamoto** [comment]
@jef 
Sorry for being late.
Currently, I think the workaround is only to shorten trigger name.
So I will consider good solution.

**Comment by jef** [comment]
It's okay! I don't mean to bother you when you're AFK. I just wanted to see if the line of thought was correct or if I missed some of the documentation.

Thanks for your help.

**Comment by jef** [comment]
Looks like @RaviHari cleared this up. Thank you all!
