### ISSUE TITLE
Controller is not working with nameOverride/fullnameOverride

### ISSUE THREAD

**Issue by sergeyshaykhullin** [argoproj-labs/argocd-notifications#295]
## Summary 

Argocd-notifications controller always tries to find `argocd-notifications-cm` and `argocd-notifications-secret`
But helm chart is overriding this names if name/fullnameOverrides exists: 
- https://github.com/argoproj/argo-helm/blob/b58209845580cfcef3a7eee2c9769eee44f1f654/charts/argocd-notifications/templates/configmap.yaml#L5
- https://github.com/argoproj/argo-helm/blob/b58209845580cfcef3a7eee2c9769eee44f1f654/charts/argocd-notifications/templates/secret.yaml#L5

Quick fix - use constant names in helm chart, but for consistency is better to have something inside controller to override sm/secret names

## Diagnostics

Helm: `argocd-notifications@1.3.2`

```
# Paste the logs from the notification controller

time="2021-06-01T12:27:00Z" level=info msg="serving metrics on port 9001" time="2021-06-01T12:27:00Z" level=info msg="loading configuration 9001" time="2021-06-01T12:27:00Z" level=warning msg="Cannot find config map argocd-notifications-cm and secret argocd-notifications-secret. Waiting when both config map and secret are created."

# Logs for the entire controller:
kubectl logs -n argocd deployment/argocd-notifications-controller
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by ryota-sakamoto** [comment]
To change name of ConfigMap and Secret is supported but not released yet. https://github.com/argoproj-labs/argocd-notifications/pull/286
So it will be able to use other name not argocd-notifications-cm after it is released
