### ISSUE TITLE
repo.GetAppDetails() is not working with name/fullnameOverride

### ISSUE THREAD

**Issue by sergeyshaykhullin** [argoproj-labs/argocd-notifications#297]
## Summary 

When used `{{(call repo.GetAppDetails).Type}}` inside template
```
time="2021-06-04T19:06:51Z"
level=error
msg="Failed to notify recipient {slack template} defined in app redacted/redacted template: app-sync-running:23:17: executing \"app-sync-running\" at <call .repo.GetAppDetails>: error calling call: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp: lookup argocd-repo-server on 10.43.0.10:53: no such host\"" app=redacted/redacted
```

## Diagnostics

I am deploying argo cd + notifications with helm chart with `fullnameOverride`. `argocd-repo-server` exists, but named `cd-repo-server`

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by ryota-sakamoto** [comment]
Hi @sergeyshaykhullin 
Would you share your helm values, please?

**Comment by sergeyshaykhullin** [comment]
@ryota-sakamoto Hmm, i think it is an error not i values (notification template). I used argocd `fullnameoverride: cd` -> `cd-repo-server` address, but notifications is trying to call `argocd-repo-server` as default

**Comment by ryota-sakamoto** [comment]
@sergeyshaykhullin 
I understand. It is supported that `argocd-repo-server` replace with other name using controller's flag.
https://github.com/argoproj-labs/argocd-notifications/blob/c461d624b4c02452e85821361bb1c4c2d2e487b7/cmd/controller.go#L119

**Comment by sergeyshaykhullin** [comment]
@ryota-sakamoto Hmm, seems like i can fix it with extra args then)

https://github.com/argoproj/argo-helm/blob/ca0a53d6ebd86bfe46ba5018410b2be08dce2bb3/charts/argocd-notifications/templates/deployment.yaml#L45

I will try

**Comment by sergeyshaykhullin** [comment]
@ryota-sakamoto Thanks a lot, this override works

Do you know how to call GetParameterValueByName with arguments? I used this example https://argocd-notifications.readthedocs.io/en/stable/templates/#repo

My template
```
{
  "title": "Test",
  "value": "{{ (call (call .repo.GetAppDetails).Helm.GetParameterValueByName "image.tag") }}",
  "short": true
}
```

But getting
```
time="2021-06-14T12:09:32Z" level=error msg="Failed to notify recipient {slack redacted} defined in app redacted/redacted: template: app-sync-running:30:34: executing \"app-sync-running\" at <.repo.GetAppDetails>: wrong number of args for GetParameterValueByName: want 1 got 0" app=redacted/redacted
```

**Comment by sergeyshaykhullin** [comment]
Seems like i forgot escaping...

**Comment by sergeyshaykhullin** [comment]
Hmm

```
time="2021-06-14T12:22:27Z" level=warning msg="Failed to parse new settings: template: app-sync-running:30: malformed character constant: 'image.tag'"
```

**Comment by sergeyshaykhullin** [comment]
No, context is also not working, seems like i am missing something...

```
(call (call .repo.GetAppDetails).Helm.GetParameterValueByName .context.imageTagParameterName)
```

**Comment by kgonyon** [comment]
Left a message in slack as well but we are using this format in our template and it is working. 
``` {{ (call .repo.GetAppDetails).Helm.GetParameterValueByName "image.tag" }} ```

**Comment by Yurevich-Andrey** [comment]
Hello. Trying to get value from values.yml file:
```
                  {
                    "name": "GET backend tag",
                    "value": "{{ (call .repo.GetAppDetails).Helm.GetParameterValueByName "backend.tag" }}"
                  }
```
```
                  {
                    "name": "GET backend tag",
                    "value": "{{ (call .repo.GetAppDetails).Helm.GetParameterValueByName "backend.tag" }}"
                  }
```

**Comment by sergeyshaykhullin** [comment]
This is the right syntax `{{ (call .repo.GetAppDetails).Helm.GetParameterValueByName "image.tag" }}`. Did you configured repo credentials?

**Comment by Aankhen** [comment]
This is related to #294. The argocd-repo-server `NetworkPolicy` expects `argocd-notifications-controller`:

https://github.com/argoproj/argo-cd/blob/363e1d2d491991fd76e23320b80d6e3bbbed94ce/manifests/install.yaml#L3798

If you either change that `NetworkPolicy` or set `nameOverride` to `argocd-notifications-controller`, it’ll be able to reach the repo server.
