### ISSUE TITLE
Show author of revision

### ISSUE THREAD

**Issue by imranismail** [argoproj-labs/argocd-notifications#30]
Is there a way for us to show the author for the revision being deployed?

**Comment by alexmt** [comment]
The revision metadata is not available in Application CRD. However `argocd-repo-server` exposes API that fetches metadata along with author and committer.

I think in most cases the notification controller is going to be installed in the same namespace where argocd components are running. So it is safe to assume that `argocd-repo-server` API is available and  the notification controller might use it to load commit info and expose it as part of `context` variable.

**Comment by imranismail** [comment]
@alexmt I'd be happy to contribute. Is there any documentation for argocd-repo-server API?

**Comment by alexmt** [comment]
Thank you @imranismail ! 

Argo CD repo server is gRPC based server. The service methods are described [here](https://github.com/argoproj/argo-cd/blob/master/reposerver/repository/repository.proto) . We  need `GetRevisionMetadata` method. To access service we can just import generated client from argo-cd repository.

I've realized that repo-server requires repository credentials. If we assume that argocd-notification-controller runs in the same namespace as argocd then repository credentials are also available in one of the secrets and we can use another argocd package to load it. 

I've added code that loads repo credentials and loads commit metadata from argocd repo server: https://github.com/alexmt/argocd-notifications/commit/578edc73e18c7cc69e0dbd0a9424bf9ec232cadb  :

```
func repoServerSample(namespace string, k8sClient kubernetes.Interface) {
	db := db.NewDB(namespace, settings.NewSettingsManager(context.Background(), k8sClient, namespace), k8sClient)
	repo, err := db.GetRepository(context.Background(), "https://github.com/argoproj/argocd-example-apps")
	if err != nil {
		log.Fatal(err)
	}
	repoClientset := apiclient.NewRepoServerClientset("argocd-repo-server:8081", 5)
	closer, repoClient, err := repoClientset.NewRepoServerClient()
	if err != nil {
		log.Fatal(err)
	}
	defer func() {
		_ = closer.Close()
	}()
	metadata, err := repoClient.GetRevisionMetadata(context.Background(), &apiclient.RepoServerRevisionMetadataRequest{
		Repo:     repo,
		Revision: "6bed858de32a0e876ec49dad1a2e3c5840d3fb07",
	})
	if err != nil {
		log.Fatal(err)
	}
	println(fmt.Sprintf("%v", metadata))
}
```

**Comment by Atharex** [comment]
Nice, this looks really useful!

So a notification like this would be possible?
<user> synced the file <service.yaml> to application <app> with commit message: <message>

**Comment by Atharex** [comment]
Also one more feature question... is it possible to distinguish during sync whether something was added or something was deleted? So a notification could be adapted to these 2 scenarios

**Comment by omerlh** [comment]
Is someone working on that? If not, I might be able to take it

**Comment by imranismail** [comment]
@omerlh I haven't started yet, you can go ahead.

**Comment by alexmt** [comment]
@Atharex , sorry I did not notice your question. Only some fields of your sample message will be available.

This feature allows getting the commit author and commit message.

The name of the user who clicked the sync button is not available. Trying to add it in this PR: https://github.com/argoproj/argo-cd/pull/3252 . If PR gets merged that user name will be available at `.app.status.operationState.operation.initiatedBy`

The exact filename is not available since manifests could by generated using helm, kustomize etc.  Argo CD stores the names of updated resources. This information is available in `.app.status.operationState.syncResult.resources`
