### ISSUE TITLE
How to subscribe to all triggers of an app using slackbot

### ISSUE THREAD

**Issue by andyyaldoo** [argoproj-labs/argocd-notifications#300]
## Summary 
The [docs](https://argocd-notifications.readthedocs.io/en/latest/bots/slack-bot/) mentioned that the syntax for the slash command as `subscribe <my-app> <optional-trigger>`. It does not really say what happen if I leave the `<optional-trigger>` empty. Does it listen to all triggers? I tried running the command without it and nothing happened. What I intend to do is to run one command to subscribe to all triggers for a particular app.

## Diagnostics

What Kubernetes provider are you using? 
> EKS

What version of Argo CD and Argo CD Notifications are you running? 
```
argocd-server: v1.8.4+28aea3d
  BuildDate: 2021-02-05T17:56:06Z
  GitCommit: 28aea3dfdede00443b52cc584814d80e8f896200
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8

argocd-notifications: 1.4.0
```

```
# Logs are too long as we have hundreds of apps and I believe it is not relevant for the bot. CMIIW
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by andyyaldoo** [comment]
I can't seem to edit the label. Should be `question` rather than `bug`

**Comment by ryota-sakamoto** [comment]
Hi @andyyaldoo 
I checked this matter, then empty trigger is not supported now.
I mean it has happened nothing when trigger is defined.

**Comment by andyyaldoo** [comment]
Thank you @ryota-sakamoto for checking. Closing this issue
