### ISSUE TITLE
When will a new release version be created?

### ISSUE THREAD

**Issue by arnouthoebreckx** [argoproj-labs/argocd-notifications#351]
### Discussed in https://github.com/argoproj-labs/argocd-notifications/discussions/350

<div type='discussions-op-text'>

<sup>Originally posted by **arnouthoebreckx** October 20, 2021</sup>
For a feature that I want to use a new version is needed of notifications-engine and argocd-notifications.
This is so that the following feature (HTML mails) can be used by us. https://github.com/argoproj/notifications-engine/pull/30

When/How would something like this be merged and released so that consumers can start using this?
</div>

**Comment by ryota-sakamoto** [comment]
released
https://github.com/argoproj-labs/argocd-notifications/releases/tag/v1.2.0
