### ISSUE TITLE
repo GetCommitMetadata fails w/ new ArgoCD repo secrets changes

### ISSUE THREAD

**Issue by tsunamishaun** [argoproj-labs/argocd-notifications#356]
## Summary 

Calls to the `repo` function specifically `.repo.GetCommitMetadata .app.status.sync.revision` fail because the repo credentials don't exist in argocd (in the same way they use to). Ever since moving to the new repo secrets templates in ArgoCD I started seeing this issue.

## Diagnostics

What Kubernetes provider are you using? 1.20

What version of Argo CD and Argo CD Notifications are you running? 2.1.2 / 1.1.1

```
argocd-notifications-controller- argocd-notifications-controller time="2021-11-09T03:37:25Z" level=error msg="Failed to notify recipient {foo } defined in app argocd/foo: template: foo:19:58: executing \"foo\" at <call .repo.GetCommitMetadata .app.status.sync.revision>: error calling call: rpc error: code = Internal desc = Failed to fetch dk1k2d9191d: `git fetch origin --tags --force` failed exit status 128: git@github.com: Permission denied (publickey).\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists." app=argocd/foo
```

Reference comment on argocd issue with similar message: https://github.com/argoproj/argo-cd/issues/2890#issuecomment-954794087
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by lukpep** [comment]
any workaround for this? Using ArgoCD 2.1.7

**Comment by tsunamishaun** [comment]
Thanks to @pasha-codefresh for updating the argocd dependency and for @alexmt for cutting a new release [v1.2.1](https://github.com/argoproj-labs/argocd-notifications/releases/tag/v1.2.1)! cc @lukpep

**Comment by lukpep** [comment]
also started working for me - thx @pasha-codefresh and @tsunamishaun for mentioning me ;-)
