### ISSUE TITLE
Teams Notifications does show emojis

### ISSUE THREAD

**Issue by Manoj0251** [argoproj-labs/argocd-notifications#388]
Teams Notifications doesn't show emojis mentioned in the templates

![image](https://user-images.githubusercontent.com/17288291/156763888-b2adf3db-a63e-44e1-9064-4f024ff70f78.png)

![image](https://user-images.githubusercontent.com/17288291/156764180-406f24bf-0b27-4775-ad6c-9e9479182839.png)

Do we have a different templates for Teams

**Comment by MaxWinterstein** [comment]
Posting your notifications configmap would help 😉 

I guess you should provide the emojis as hex codes , see https://stackoverflow.com/questions/53384141/teams-webhook-send-emojis-in-notifications

e.g.
```yaml
      title: Application {{.app.metadata.name}} has been successfully synced &#1F60D;
```

**Comment by Manoj0251** [comment]
Tried  with hexcode and it is working ..2705 is the code for check mark button
&#x**2705**;
