### ISSUE TITLE
add support for proxy settings

### ISSUE THREAD

**Issue by lkeijser** [argoproj-labs/argocd-notifications#42]
Like argocd, allow for webproxy settings by honoring HTTP_PROXY, HTTPS_PROXY and NO_PROXY environment variables to send notifications to e.g. slack through a webproxy.

**Comment by roelofjansen** [comment]
Hi, is it correct that setting the HTTP_PROXY etc. variables in the argocd-notifications pod/container has no effect currently?

**Comment by lkeijser** [comment]
@roelofjansen That's correct. Hence, this issue.

**Comment by samirmajen** [comment]
This already works, tested using HTTPS_PROXY, HTTP_PROXY and NO_PROXY with a webhook to slack, using argocd-notification v.0.7.0

**Comment by lkeijser** [comment]
@samirmajen no, it doesn't. Probably it works for you if traffic isn't blocked/dropped when bypassing a proxy, which is the case in my situation. But HTTP_PROXY etc. isn't being honored. Tried http_proxy/https_proxy as well, to no effect:

`time="2020-06-24T11:23:56Z" level=error msg="Failed to notify recipient slack:argocd defined in app argocd/test-adl-connector-belgie: Post https://slack.com/api/chat.postMessage: dial tcp 3.10.95.11:443: connect: connection timed out" app=argocd/test-adl-connector-belgie`

**Comment by 0gajun** [comment]
I've tried to fix this issue in #106 :)

**Comment by lkeijser** [comment]
Any updates on this?
