### ISSUE TITLE
Where's support  SMTP, Telegram ???

### ISSUE THREAD

**Issue by iyurev** [argoproj-labs/argocd-notifications#46]
In project overview written  - "Argo CD specific notification system that continuously monitors Argo CD applications and aims to integrate with various notification services such as Slack, SMTP, Telegram, Discord, etc." .

So what about support telegram notification ?? Or maybe I have missed something in documentation ??)

**Comment by pydo** [comment]
Not sure why the docs say Telegram and Discord, but looking at the code https://github.com/argoproj-labs/argocd-notifications/blob/master/notifiers/notifiers.go#L28
they only seem to support: `smtp`, 'slack' and `opsgenie`.

**Comment by alexmt** [comment]
Thank you for clarification @pydo . Updated README.md in https://github.com/argoproj-labs/argocd-notifications/pull/50 to remove confusion
