### ISSUE TITLE
Failed to notify recipient slack. 

### ISSUE THREAD

**Issue by pnduati** [argoproj-labs/argocd-notifications#65]
Showing logs from **argocd-notifications-controller** 
time="2020-03-20T06:31:56Z" level=info msg="Trigger on-sync-running result: false" app=argocd/attribution-service
time="2020-03-20T06:31:56Z" level=info msg="Trigger on-sync-succeeded result: true" app=argocd/attribution-service
time="2020-03-20T06:31:56Z" level=info msg="Sending on-sync-succeeded notification" app=argocd/attribution-service
**time="2020-03-20T06:31:56Z" level=error msg="Failed to notify recipient slack:argocd-atlas-releases defined in app argocd/attribution-service: invalid character '{' after array element"** app=argocd/attribution-service

**argocd-notification-cm.yaml**
```
apiVersion: v1
data:
  config.yaml: |
    triggers:
      # enable sync status notifications triggers
      - name: on-sync-status-unknown
        enabled: true
        template: app-sync-status-unknown
      - name: on-sync-failed
        enabled: true
        template: app-sync-failed
      - name: on-sync-succeeded
        enabled: true                
        template: app-sync-succeeded
      - name: on-health-degraded
        enabled: true
        template: app-health-degraded
      - name: on-sync-running	
        enabled: true
        template: app-sync-running
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: argo-cd
  name: argocd-notifications-cm
  namespace: argocd
---
**Adding the annotation to the argocd application.**
kubectl patch app attribution-service -n argocd -p '{"metadata":{"annotations":{"recipients.argocd-notifications.argoproj.io":"slack:argocd-atlas-releases"}}}' --type merge

**Comment by ArjonBu** [comment]
@alexmt  I keep getting "invalid character '{' after array element". 

`apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  config.yaml: |
    subscriptions:
      - recipients:
        - slack:my-channel
    triggers:
      - name: on-sync-succeeded
        enabled: true
      - name: on-sync-failed
        enabled: true
      - name: on-sync-status-unknown
        enabled: true
      - name: on-health-degraded
        enabled: true
      - name: on-sync-status-unknown
        enabled: true
`

I am using version 0.7
