### ISSUE TITLE
Any way to access deployed images and tags

### ISSUE THREAD

**Issue by Unb9rn** [argoproj-labs/argocd-notifications#78]
Is there any way to send app's images and tags via generic webhook?
I've tried setting up a template like this: {{.app.status.resources.summary.images}}
But it won't work:
` <.app.status.resources.summary.images>: can't evaluate field summary in type interface {}`

**Comment by alexmt** [comment]
Templates allow using [sprig](http://masterminds.github.io/sprig/) functions. You might use join [join](http://masterminds.github.io/sprig/string_slice.html) function:
```
{{.app.status.resources.summary.images | join ", " }}
```
