### ISSUE TITLE
Github Integration

### ISSUE THREAD

**Issue by daurnimator** [argoproj-labs/argocd-notifications#99]
Attempting to set up the commit status webhook I found that it required a github OAuth app + github user to act as.
Instead, I'd like to use a [Github app](https://developer.github.com/apps/differences-between-apps/) to set the commit statuses. However, the tokens are short lived, and you need an extra dance to get from long lived private key to application installation token.

```sh
# Create JWT from long lived secret
# will have max lifetime of 10 minutes
# example script at https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app
JWT=$(ruby github-token.rb)

# Get installation token
# they seem to have a lifetime of an hour
TOKEN=$(curl -X POST \
  -H "Authorization: Bearer $JWT" \
  -H "Accept: application/vnd.github.machine-man-preview+json" \
  https://api.github.com/app/installations/$INSTALLATION_ID/access_tokens
  | jq .token)

# Set a commit status
curl https://api.github.com/repos/someorg/somerepo/statuses/somecommitSHA \
    -H Authorization:" token $TOKEN" -d '{"state": "success"}'
```

**Comment by RichiCoder1** [comment]
I'd actually be interested in trying this too, except using the Deployments API

**Comment by alexmt** [comment]
Thank for pointing this out. Integration with Github is important definitely deserves custom support if necessary. Will work on it in 1.1 after next milestone.

**Comment by ryota-sakamoto** [comment]
Hi @alexmt 
I want to do this task.

**Comment by alexmt** [comment]
@ryota-sakamoto , FYI. Argo CD is getting similar support in this PR https://github.com/argoproj/argo-cd/pull/5355

**Comment by alexmt** [comment]
Impemented by https://github.com/argoproj-labs/argocd-notifications/pull/180
